name: Version Increment

on:
  push:
    branches:
      - development

jobs:
  version:
    runs-on: ubuntu-latest
    #if: "startsWith(github.event.head_commit.message, '[PACKAGE]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: 'Update package patch version'
        run: |
          echo ${{ github.event.head_commit.message  }}
