name: Version Increment

on:
  push:
    branches:
      - development

jobs:
  version:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'Update apollo_package schema')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: 'Update package patch version'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version patch -m "[RELEASE] %s"
          git push https://@github.com/LianeRada/testing-repo.git HEAD:development --follow-tags
