name: Node.js Package

on:
  push:
    branches:
      - development

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    ##if: "startsWith(github.event.head_commit.message, '[RELEASE]')"
    # steps:
    #   - uses: actions/checkout@v2
    #   - uses: actions/setup-node@v1
    #     with:
    #       node-version: 12
    #       registry-url: https://npm.pkg.github.com/
    #       scope: '@LianeRada'
    #   - run: npm publish package
    #     env:
    #       NODE_AUTH_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      # - name: Get changed files
      #   id: changed-files
      #   uses: tj-actions/changed-files@v19

      # - name: List all changed files
      #   run: |
      #     for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
      #       echo "$file was changed"
      #     done

      - name: Get changed schema files
        id: changed-files
        uses: tj-actions/changed-files@v19
        with:
          files: |
            schemas/*
      
      - name: Generate prisma if any of the above changed
        #if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "${{ steps.changed-files.outputs }}"

      # - name: List all changed files
      #   if: contains(steps.changed-files.outputs.modified_files, '*.prisma')
      #   run: |
      #     echo "Schema was changed. Generating new file."
      # - name: Copy the Readmes
      #   run: |
      #     find ./myfolder/ -type f -name "README.md" | while read fname; do
      #       dirname=`dirname "$fname"`
      #       foldername=`basename "$dirname"`
      #       filename=`basename "$fname"`
      #       newname=`echo "$dirname" | sed -e "s/ /_/g"`
      #       cp "./out/schema/schema.gql" "./docs/_myfolder/${foldername}.md"
      #     done
      # - name: Commit files
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git commit -m "Add changes" -a
      #     git push https://@github.com/LianeRada/testing-repo.git HEAD:development --follow-tags
