name: Update package schema

on:
  push:
    branches:
      - development

jobs:
  #publish-gpr:
  update-package:
    runs-on: ubuntu-latest
    ##if: "startsWith(github.event.head_commit.message, '[RELEASE]')"
    # steps:
    #   - uses: actions/checkout@v2
    #   - uses: actions/setup-node@v1
    #     with:
    #       node-version: 12
    #       registry-url: https://npm.pkg.github.com/
    #       scope: '@LianeRada'
    #   - run: npm publish package
    #     env:
    #       NODE_AUTH_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Get changed schema files
        id: changed-files
        uses: tj-actions/changed-files@v19
        with:
          files: |
            schemas/*
      
      - name: Generate prisma if any of the above changed
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Schema was changed. Generating new file. (docker-start/prisma-generate)"

      - name: Copy schema to package
        run: |
          cp "./out/schema/schema.gql" "./apollo_package/schema.gql"

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update apollo_package schema"
          git push https://@github.com/LianeRada/testing-repo.git HEAD:development --follow-tags
